name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install native dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y pkg-config libfontconfig1-dev
    - name: Install Rust components
      run: rustup component add rustfmt clippy
    - name: Check code guidelines
      run: scripts/enforce_code_guidelines
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Check lints
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose
